export const LOADINGOFF = "LOADINGOFF";
export const LOADINGON = "LOADINGON";
export const USERDATA = "USERDATA";
export const CLEARDATA = "CLEARDATA";
export const TEST_LESSON_DATA = "TEST_LESSON_DATA";
export const TEACHER_STUDENTS = "TEACHER_STUDENTS";
