// export default imagepaths
 
export {default as USER} from './assets/img/user/user.jpg';
export {default as USER_1} from './assets/img/user/user1.jpg';
export {default as USER_2} from './assets/img/user/user2.jpg';
export {default as USER_3} from './assets/img/user/user3.jpg';
export {default as USER_4} from './assets/img/user/user4.jpg';
export {default as USER_5} from './assets/img/user/user5.jpg';
export {default as USER_7} from './assets/img/user/user7.jpg';
export {default as USER_8} from './assets/img/user/user8.jpg';
export {default as USER_9} from './assets/img/user/user9.jpg';
export {default as USER_11} from './assets/img/user/user11.jpg';
export {default as USER_12} from './assets/img/user/user12.jpg';
export {default as AVATAR_06} from './assets/img/profiles/avatar-06.jpg';
export {default as AVATAR_07} from './assets/img/profiles/avatar-07.jpg';
export {default as AVATAR_08} from './assets/img/profiles/avatar-08.jpg';
export {default as AVATAR_12} from './assets/img/profiles/avatar-12.jpg';
export {default as AVATAR_13} from './assets/img/profiles/avatar-13.jpg';
export {default as AVATAR_14} from './assets/img/profiles/avatar-14.jpg';
export {default as AVATAR_17} from './assets/img/profiles/avatar-17.jpg';
export {default as AVATAR_18} from './assets/img/profiles/avatar-18.jpg';
export {default as BLOG_01} from './assets/img/blog/blog-01.jpg';
export {default as BLOG_02} from './assets/img/blog/blog-02.jpg';
export {default as BLOG_03} from './assets/img/blog/blog-03.jpg';
export {default as IMG_01} from './assets/img/img-01.jpg';
export {default as US_FLAG} from './assets/img/flags/us.png'
export {default as ES_FLAG} from './assets/img/flags/es.png'
export {default as FR_FLAG} from './assets/img/flags/fr.png'
export {default as DE_FLAG} from './assets/img/flags/de.png'
export {default as AdminLogo} from './assets/img/logo-white.svg'
